namespace SDV_DotDispenser.Defines
{
    public enum EInput
    {
        OP_BUTTON_START = 0,
        OP_BUTTON_STOP = 1,
        OP_BUTTON_RESET = 2,
        OP_SWITCH_EMO = 3,
        OP_SWITCH_AUTO = 4,
        OP_SWITCH_MANUAL = 5,
        MAIN_PANEL_FAN_RUN_1 = 6,
        MAIN_PANEL_FAN_RUN_2 = 7,
        SMOKE_DETECT_RUN = 8,
        SMOKE_DETECT_ALARM = 9,
        SMOKE_DETECT_TEMP_HIGH_ALARM = 10,
        SMOKE_DETECT_TEMP_HIGH_WARN = 11,
        SPARE_IN12 = 12,
        SERVO_ON = 13,
        MAIN_BREAKER_TRIP = 14,
        MAIN_CDA_CHECK = 15,

        DOOR_CLOSE_FRONT_LEFT = 16,
        DOOR_LOCK_FRONT_LEFT = 17,
        DOOR_CLOSE_FRONT_RIGHT = 18,
        DOOR_LOCK_FRONT_RIGHT = 19,
        DOOR_CLOSE_LEFT_FRONT = 20,
        DOOR_LOCK_LEFT_FRONT = 21,
        DOOR_CLOSE_LEFT_REAR = 22,
        DOOR_LOCK_LEFT_REAR = 23,
        DOOR_CLOSE_REAR_LEFT = 24,
        DOOR_LOCK_REAR_LEFT = 25,
        DOOR_CLOSE_REAR_RIGHT = 26,
        DOOR_LOCK_REAR_RIGHT = 27,
        LIGHT_CURTAIN_LEFT_DETECT = 28,
        LIGHT_CURTAIN_RIGHT_DETECT = 29,
        SW_START_LEFT = 30,
        SW_START_RIGHT = 31,

        PLASMA_STATUS_1 = 32,
        PLASMA_STATUS_2 = 33,
        PLASMA_STATUS_3 = 34,
        PLASMA_STATUS_4 = 35,
        SPARE_IN36 = 36,
        SPARE_IN37 = 37,
        JETTING_OUT_1 = 38,
        JETTING_OUT_2 = 39,
        JETTING_OUT_3 = 40,
        JETTING_OUT_4 = 41,
        SPARE_IN42 = 42,
        SPARE_IN43 = 43,
        UV_CURE_TEMP_ALARM = 44,
        UV_CURE_LED_ALARM = 45,
        UV_CURE_LEF_ON_OK = 46,
        SPARE_IN47 = 47,

        PLASMA_COVER_RIGHT = 48,
        PLASMA_COVER_LEFT = 49,
        SYLINGER_EPOXY_CHECK = 50,
        SPARE_IN51 = 51,
        NOZZLE_CLEANER_UP = 52,
        NOZZLE_CLEANER_DOWN = 53,
        NOZZLE_CLEANER_WIPE_CHECK = 54,
        SPARE_IN55 = 55,
        UV_CURE_FW = 56,
        UV_CURE_BW = 57,
        TRANSFER_HAND_1_UP = 58,
        TRANSFER_HAND_1_DOWN = 59,
        TRANSFER_HAND_2_UP = 60,
        TRANSFER_HAND_2_DOWN = 61,
        TRANSFER_HAND_1_VAC_ON = 62,
        TRANSFER_HAND_2_VAC_ON = 63,

        STAGE_L_LEFT_VAC_ON = 64,
        STAGE_L_RIGHT_VAC_ON = 65,
        STAGE_R_LEFT_VAC_ON = 66,
        STAGE_R_RIGHT_VAC_ON = 67,
        SPARE_IN68 = 68,
        SPARE_IN69 = 69,
        SPARE_IN70 = 70,
        SPARE_IN71 = 71,
        SPARE_IN72 = 72,
        SPARE_IN73 = 73,
        SPARE_IN74 = 74,
        SPARE_IN75 = 75,
        SPARE_IN76 = 76,
        MAIN_N2_CDA_CHECK = 77,
        PLASMA_CDA_CHECK = 78,
        PLASMA_N2_CDA_CHECK = 79,
    }
}
