namespace SDV_DotDispenser.Defines
{
    public enum EOutput
    {
        OP_START_LAMP = 0,
        OP_STOP_LAMP = 1,
        OP_RESET_LAMP = 2,
        SPARE_OUT3 = 3,
        OP_KEY_SW_LOCK = 4,
        SPARE_OUT5 = 5,
        TOWER_LAMP_RED = 6,
        TOWER_LAMP_YELLOW = 7,
        TOWER_LAMP_GREEN = 8,
        BUZZER1_ON = 9,
        BUZZER2_ON = 10,
        BUZZER3_ON = 11,
        BUZZER4_ON = 12,
        SPARE_OUT13 = 13,
        SW_START_LEFT_LAMP = 14,
        SW_START_RIGHT_LAMP = 15,

        EQP_STOP = 16,
        LIGHT_CURTAIN_LEFT_MUTING_1 = 17,
        LIGHT_CURTAIN_LEFT_MUTING_2 = 18,
        LIGHT_CURTAIN_RIGHT_MUTING_1 = 19,
        LIGHT_CURTAIN_RIGHT_MUTING_2 = 20,
        SPARE_OUT21 = 21,
        PLASMA_RUN = 22,
        PLASMA_REMOTE = 23,
        PLASMA_N2_SOL = 24,
        PLASMA_CDA_SOL = 25,
        PLASMA_REBOOT = 26,
        OUT_SPARE27 = 27,
        JETTING_ACTIVE = 28,
        JETTING_IN1 = 29,
        JETTING_IN2 = 30,
        JETTING_IN3 = 31,

        NOZZLE_CLEANER_ROLL_CW = 32,
        NOZZLE_CLEANER_ROLL_CCW = 33,
        UV_CURE_LED_ON_OFF = 34,
        SPARE_OUT35 = 35,
        PLASMA_CYL_FW = 36,
        PLASMA_CYL_BW = 37,
        TRANSFER_HAND_1_UP = 38,
        TRANSFER_HAND_1_DOWN = 39,
        TRANSFER_HAND_2_UP = 40,
        TRANSFER_HAND_2_DOWN = 41,
        UV_CURE_FW = 42,
        UV_CURE_BW = 43,
        NOZZLE_CLEANER_UP = 44,
        SPARE_OUT45 = 45,
        SPARE_OUT46 = 46,
        SPARE_OUT47 = 47,

        STAGE_L_LEFT_VAC_ON = 48,
        STAGE_L_LEFT_PURGE = 49,
        STAGE_L_RIGHT_VAC_ON = 50,
        STAGE_L_RIGHT_PURGE = 51,
        STAGE_R_LEFT_VAC_ON = 52,
        STAGE_R_LEFT_PURGE = 53,
        STAGE_R_RIGHT_VAC_ON = 54,
        STAGE_R_RIGHT_PURGE = 55,
        TRANSFER_HAND_1_VAC_ON = 56,
        TRANSFER_HAND_1_PURGE = 57,
        TRANSFER_HAND_2_VAC_ON = 58,
        TRANSFER_HAND_2_PURGE = 59,
        SPARE_OUT60 = 60,
        SPARE_OUT61 = 61,
        UV_CURE_COOLING_AIR_BLOW = 62,
        SPARE_OUT63 = 63,
    }
}
