namespace SDV_MoldingInjection.Defines
{
    public enum EHeadInput
    {
        CYL_UP_POS = 0,
        CYL_DONW_POS = 1,
        GATE_OPEN = 2,
        GATE_CLOSE = 3,
        ASSEMBLE_CHECK = 4,
        SYRINGE_CHECK = 5,
        SPARE_IN_6 = 6,
        SYRINGGE_AIR = 7,
        SYRINGE_AIR = 8,
        SPARE_IN_9 = 9,
    }

    public enum EMachineInput
    {
        OP_SW_START = 0,
        OP_SW_STOP = 1,
        OP_SW_RESET = 2,
        OP_SW_EMO = 3,
        OP_KEY_SW_AUTO = 4,
        OP_KEY_SW_TEACH = 5,
        MAIN_PANEL_FAN_RUN1 = 6,
        MAIN_PANEL_FAN_RUN2 = 7,
        SMOKE_DETECT_RUN = 8,
        SMOKE_DETECT_DETECT_ALARM = 9,
        SMOKE_DETECT_TEMP_HIGH_ALARM = 10,
        SMOKE_DETECT_TEMP_HIGH_WARNING = 11,
        PANEL_CLOSE_CHECK = 12,
        SERVO_ON = 13,
        MAIN_BREAKER_TRIP = 14,
        MAIN_CDA_CHECK = 15,

        DOOR_CLOSE_LEFT = 16,
        DOOR_LOCK_LEFT = 17,
        DOOR_CLOSE_RIGHT = 18,
        DOOR_LOCK_RIGHT = 19,
        MAIN_PANEL_CLOSE_CHECK = 20,
        MAIN_BREAKER_TRIP_EBOX = 21,
        MAIN_PANEL_FAN_RUN1_EBOX = 22,
        MAIN_PANEL_FAN_RUN2_EBOX = 23,
        MAIN_PANEL_FAN_RUN3_EBOX = 24,
        MAIN_PANEL_FAN_RUN4_EBOX = 25,
        SMOKE_DETECT_RUN_EBOX = 26,
        SMOKE_DETECT_DETECT_ALARM_EBOX = 27,
        SMOKE_DETECT_TEMP_HIGH_ALARM_EBOX = 28,
        SMOKE_DETECT_TEMP_HIGH_WARNING_EBOX = 29,
        SPARE_IN_30 = 30,
        SPARE_IN_31 = 31,

        NOZZLE1_TOUCH_DETECT = 32,
        NOZZLE2_TOUCH_DETECT = 33,
        NOZZLE3_TOUCH_DETECT = 34,
        NOZZLE4_TOUCH_DETECT = 35,
        NOZZLE1_CLEAN_CHECK = 36,
        NOZZLE2_CLEAN_CHECK = 37,
        NOZZLE3_CLEAN_CHECK = 38,
        NOZZLE4_CLEAN_CHECK = 39,
        JIG1_DETECT = 40,
        JIG2_DETECT = 41,
        JIG3_DETECT = 42,
        JIG4_DETECT = 43,
        ANGLE_VALVE_OPEN = 44,
        ANGLE_VALVE_CLOSE = 45,
        BELLOWS_UP = 46,
        BELLOWS_DOWN = 47,

        VAC_PUMP_RUN = 48,
        VAC_PUMP_ALARM = 49,
        VAC_CHAMBER_PURGE_ON = 50,
        VAC_CHAMBER_OPEN = 51,
        VAC_CHAMBER_CLOSE = 52,
        SPARE_IN_53 = 53,
        SPARE_IN_54 = 54,
        SPARE_IN_55 = 55,
        SPARE_IN_56 = 56,
        SPARE_IN_57 = 57,
        SPARE_IN_58 = 58,
        SYLINGE_HEAD_CDA_CHECK = 59,
        PUMP_CDA_CHECK = 60,
        PUMP_VENT_CDA_CHECK = 61,
        PUMP_FAN_RUN1 = 62,
        PUMP_FAN_RUN2 = 63
    }
}
