using System.ComponentModel;

namespace SDV_MoldingInjection.Defines
{
    /// <summary>
    /// Đặt Tên theo quy tắc: CATEGORY_POSITION_DEVICE_DESCRIPTION1_DESCRIPTION2_ERRORMODE.(samsung yêu cầu)
    /// CATEGORY_POSITION_DEVICE_DESCRIPTION1_DESCRIPTION2_ERRORMODE.
    /// Category (2 ký tự): VC VA MO IN VI CY SE CO DO TE EM UT OP ET EF.
    /// ErrorMode (bảng): ERROR (lỗi hoàn thành/kiểm tra), MARK_NG, UP_NG, OPEN, SWITCH_ON, SERVO_OFF, TEMP_OVER, TIMEOUT.
    /// Position: MAIN SUB LOADER UNLOADER PRESS INSPECTION BUFFER CONVEYOR.
    /// </summary>
    public enum EWarning
    {
        //--------- 20 -> 499 : Global ---------
        ET_MAIN_STG_SYS_MARK_NG = 20,
        [Description("IN16,IN18,IN69,IN71")]
        DO_MAIN_DOOR_INTERLOCK_OPEN,
        [Description("IN17,IN19,IN70,IN72")]
        DO_MAIN_DOOR_LOCK_SWITCH_ON,
        MO_MAIN_STG_XY_TARGET_ERROR,
        [Description("IN11")]
        TE_MAIN_CP_SENSOR_TEMP_OVER,
        [Description("IN04")]
        OP_MAIN_CP_KEY_AUTO_ERROR,
        [Description("IN04")]
        OP_MAIN_STG_MODE_AUTO_ERROR,

        //--------- 500 -> 999 : Mold ---------
        CY_MAIN_STG_DOOR_MC_OPEN_OPEN = 500,
        CY_MAIN_STG_DOOR_MC_OPEN_SEQ_ERROR,
        CY_MAIN_STG_DOOR_MC_CLOSE_OPEN,
        CY_MAIN_STG_DOOR_MC_CLOSE_SEQ_ERROR,

        MO_MAIN_STG_X_HOME_TIMEOUT = 550,
        MO_MAIN_STG_X_READY_TIMEOUT,
        MO_MAIN_STG_X_INJECT_TIMEOUT,
        MO_MAIN_STG_X_DUMMY_TIMEOUT,
        MO_MAIN_STG_X_DW_H13_TIMEOUT,
        MO_MAIN_STG_X_DW_H24_TIMEOUT,
        MO_MAIN_STG_X_NEEDLECLN_TIMEOUT,

        MO_MAIN_STG_Y_HOME_TIMEOUT = 600,
        MO_MAIN_STG_Y_READY_TIMEOUT,
        MO_MAIN_STG_Y_INJECT_TIMEOUT,
        MO_MAIN_STG_Y_DUMMY_TIMEOUT,
        MO_MAIN_STG_Y_NEEDLECLN_TIMEOUT,

        MO_SUB_H01_IDX_Z_HOME_TIMEOUT = 650,
        MO_SUB_H01_IDX_Z_SAFE_TIMEOUT,
        MO_SUB_H01_IDX_Z_INJECT_TIMEOUT,
        MO_SUB_H01_IDX_Z_DUMMY_TIMEOUT,
        MO_SUB_H01_IDX_Z_NEEDLECLN_TIMEOUT,
        MO_SUB_H01_IDX_Z_DW_TIMEOUT,
        MO_SUB_H01_IDX_Z_BUBBLE_TIMEOUT,
        MO_SUB_H01_IDX_Z_ASSY_TIMEOUT,
        MO_SUB_H01_IDX_Z_ADDTAIL_UP_NG,

        MO_SUB_H02_IDX_Z_HOME_TIMEOUT = 700,
        MO_SUB_H02_IDX_Z_SAFE_TIMEOUT,
        MO_SUB_H02_IDX_Z_INJECT_TIMEOUT,
        MO_SUB_H02_IDX_Z_DUMMY_TIMEOUT,
        MO_SUB_H02_IDX_Z_NEEDLECLN_TIMEOUT,
        MO_SUB_H02_IDX_Z_DW_TIMEOUT,
        MO_SUB_H02_IDX_Z_BUBBLE_TIMEOUT,
        MO_SUB_H02_IDX_Z_ASSY_TIMEOUT,
        MO_SUB_H02_IDX_Z_ADDTAIL_UP_NG,

        MO_SUB_H03_IDX_Z_HOME_TIMEOUT = 750,
        MO_SUB_H03_IDX_Z_SAFE_TIMEOUT,
        MO_SUB_H03_IDX_Z_INJECT_TIMEOUT,
        MO_SUB_H03_IDX_Z_DUMMY_TIMEOUT,
        MO_SUB_H03_IDX_Z_NEEDLECLN_TIMEOUT,
        MO_SUB_H03_IDX_Z_DW_TIMEOUT,
        MO_SUB_H03_IDX_Z_BUBBLE_TIMEOUT,
        MO_SUB_H03_IDX_Z_ASSY_TIMEOUT,
        MO_SUB_H03_IDX_Z_ADDTAIL_UP_NG,

        MO_SUB_H04_IDX_Z_HOME_TIMEOUT = 800,
        MO_SUB_H04_IDX_Z_SAFE_TIMEOUT,
        MO_SUB_H04_IDX_Z_INJECT_TIMEOUT,
        MO_SUB_H04_IDX_Z_DUMMY_TIMEOUT,
        MO_SUB_H04_IDX_Z_NEEDLECLN_TIMEOUT,
        MO_SUB_H04_IDX_Z_DW_TIMEOUT,
        MO_SUB_H04_IDX_Z_BUBBLE_TIMEOUT,
        MO_SUB_H04_IDX_Z_ASSY_TIMEOUT,
        MO_SUB_H04_IDX_Z_ADDTAIL_UP_NG,

        CY_MAIN_STG_MC_BELLOW_DOWN_ERROR = 900,
        CY_MAIN_STG_MC_BELLOW_UP_UP_NG,
        VC_MAIN_STG_MC_VAC_LINE_OPEN,
        SE_MAIN_STG_MC_LEFT_TILT_OPEN,
        SE_MAIN_STG_MC_RIGHT_TILT_OPEN,
        EF_MAIN_STG_MC_LEFT_INJECT_ERROR,
        EF_MAIN_STG_MC_RIGHT_INJECT_ERROR,

        CY_MAIN_STG_NOZZLE_GRIP_ERROR,
        CY_MAIN_STG_NOZZLE_UNGRIP_ERROR,

        //--------- 1000 -> 1499 : Dry ---------
        CY_MAIN_BUF_LINE_VALVE_CLOSE_ERROR = 1000,
        CY_MAIN_BUF_LINE_VALVE_OPEN_ERROR,
        MO_MAIN_STG_DRYPUMP_RUN_TIMEOUT,
        VA_MAIN_STG_CALIB_REQUIRED_ERROR,
        SE_MAIN_STG_DRY_UNLD_ERROR,
        SE_MAIN_STG_DRY_L_TILT_OPEN,
        SE_MAIN_STG_DRY_L_BODY_OPEN,
        SE_MAIN_STG_DRY_R_TILT_OPEN,
        SE_MAIN_STG_DRY_R_BODY_OPEN,

        //--------- 1500 -> 1999 : Head 1 ---------
        MO_SUB_H01_IDX_P_HOME_TIMEOUT = 1500,
        MO_SUB_H01_IDX_G_HOME_TIMEOUT,
        [Description("HEAD1_IN00")]
        CY_SUB_H01_SYR_PISTON_UP_UP_NG,
        [Description("HEAD1_IN01")]
        CY_SUB_H01_SYR_PISTON_DOWN_ERROR,
        [Description("HEAD1_IN04")]
        MO_SUB_H01_SYR_ASSY_CHECK_TIMEOUT,
        [Description("HEAD1_IN04")]
        MO_SUB_H01_SYR_DISASSY_CHECK_TIMEOUT,
        VA_SUB_H01_SYR_BAL_STAB_ERROR,
        VA_SUB_H01_SYR_BAL_REQ_ERROR,
        VA_SUB_H01_SYR_BAL_ZERO_ERROR,
        /// <summary>Balance data fail or syringe empty</summary>
        VA_SUB_H01_SYR_BAL_WEIGH_ERROR,
        MO_SUB_H01_IDX_P_BUBBLE_TIMEOUT,
        MO_SUB_H01_IDX_G_BUBBLE_TIMEOUT,
        MO_SUB_H01_IDX_P_OVER_BASE_ERROR,
        [Description("HEAD1_IN05")]
        SE_SUB_H01_SYR_BODY_OPEN,
        VA_SUB_H01_SYR_FILL_TIMEOUT,
        [Description("HEAD1_IN06")]
        SE_SUB_H01_SYR_AIR_OPEN,

        //--------- 2000 -> 2499 : Head 2 ---------
        MO_SUB_H02_IDX_P_HOME_TIMEOUT = 2000,
        MO_SUB_H02_IDX_G_HOME_TIMEOUT,
        [Description("HEAD2_IN00")]
        CY_SUB_H02_SYR_PISTON_UP_UP_NG,
        [Description("HEAD2_IN01")]
        CY_SUB_H02_SYR_PISTON_DOWN_ERROR,
        [Description("HEAD2_IN04")]
        MO_SUB_H02_SYR_ASSY_CHECK_TIMEOUT,
        [Description("HEAD2_IN04")]
        MO_SUB_H02_SYR_DISASSY_CHECK_TIMEOUT,
        VA_SUB_H02_SYR_BAL_STAB_ERROR,
        VA_SUB_H02_SYR_BAL_REQ_ERROR,
        VA_SUB_H02_SYR_BAL_ZERO_ERROR,
        /// <summary>Balance data fail or syringe empty</summary>
        VA_SUB_H02_SYR_BAL_WEIGH_ERROR,
        MO_SUB_H02_IDX_P_BUBBLE_TIMEOUT,
        MO_SUB_H02_IDX_G_BUBBLE_TIMEOUT,
        MO_SUB_H02_IDX_P_OVER_BASE_ERROR,
        [Description("HEAD2_IN05")]
        SE_SUB_H02_SYR_BODY_OPEN,
        VA_SUB_H02_SYR_FILL_TIMEOUT,
        [Description("HEAD2_IN06")]
        SE_SUB_H02_SYR_AIR_OPEN,

        //--------- 2500 -> 2999 : Head 3 ---------
        MO_SUB_H03_IDX_P_HOME_TIMEOUT = 2500,
        MO_SUB_H03_IDX_G_HOME_TIMEOUT,
        [Description("HEAD3_IN00")]
        CY_SUB_H03_SYR_PISTON_UP_UP_NG,
        [Description("HEAD3_IN01")]
        CY_SUB_H03_SYR_PISTON_DOWN_ERROR,
        [Description("HEAD3_IN04")]
        MO_SUB_H03_SYR_ASSY_CHECK_TIMEOUT,
        [Description("HEAD3_IN04")]
        MO_SUB_H03_SYR_DISASSY_CHECK_TIMEOUT,
        VA_SUB_H03_SYR_BAL_STAB_ERROR,
        VA_SUB_H03_SYR_BAL_REQ_ERROR,
        VA_SUB_H03_SYR_BAL_ZERO_ERROR,
        /// <summary>Balance data fail or syringe empty</summary>
        VA_SUB_H03_SYR_BAL_WEIGH_ERROR,
        MO_SUB_H03_IDX_P_BUBBLE_TIMEOUT,
        MO_SUB_H03_IDX_G_BUBBLE_TIMEOUT,
        MO_SUB_H03_IDX_P_OVER_BASE_ERROR,
        [Description("HEAD3_IN05")]
        SE_SUB_H03_SYR_BODY_OPEN,
        VA_SUB_H03_SYR_FILL_TIMEOUT,
        [Description("HEAD3_IN06")]
        SE_SUB_H03_SYR_AIR_OPEN,

        //--------- 3000 -> 3499 : Head 4 ---------
        MO_SUB_H04_IDX_P_HOME_TIMEOUT = 3000,
        MO_SUB_H04_IDX_G_HOME_TIMEOUT,
        [Description("HEAD4_IN00")]
        CY_SUB_H04_SYR_PISTON_UP_UP_NG,
        [Description("HEAD4_IN01")]
        CY_SUB_H04_SYR_PISTON_DOWN_ERROR,
        [Description("HEAD4_IN04")]
        MO_SUB_H04_SYR_ASSY_CHECK_TIMEOUT,
        [Description("HEAD4_IN04")]
        MO_SUB_H04_SYR_DISASSY_CHECK_TIMEOUT,
        VA_SUB_H04_SYR_BAL_STAB_ERROR,
        VA_SUB_H04_SYR_BAL_REQ_ERROR,
        VA_SUB_H04_SYR_BAL_ZERO_ERROR,
        /// <summary>Balance data fail or syringe empty</summary>
        VA_SUB_H04_SYR_BAL_WEIGH_ERROR,
        MO_SUB_H04_IDX_P_BUBBLE_TIMEOUT,
        MO_SUB_H04_IDX_G_BUBBLE_TIMEOUT,
        MO_SUB_H04_IDX_P_OVER_BASE_ERROR,
        [Description("HEAD4_IN05")]
        SE_SUB_H04_SYR_BODY_OPEN,
        VA_SUB_H04_SYR_FILL_TIMEOUT,
        [Description("HEAD4_IN06")]
        SE_SUB_H04_SYR_AIR_OPEN,
    }
}
