using System.ComponentModel;

namespace SDV_MoldingInjection.Defines
{
    /// <summary>
    /// Đặt Tên theo quy tắc: CATEGORY_POSITION_DEVICE_DESCRIPTION1_DESCRIPTION2_ERRORMODE.(samsung yêu cầu)
    /// CATEGORY_POSITION_DEVICE_DESCRIPTION1_DESCRIPTION2_ERRORMODE.
    /// Category (2 ký tự): VC VA MO IN VI CY SE CO DO TE EM UT OP ET EF.
    /// ErrorMode (bảng): ERROR, MARK_NG, UP_NG, OPEN, NOT_DETECT, SWITCH_ON, SERVO_OFF, TEMP_OVER, TIMEOUT.
    /// Position: MAIN SUB LOADER UNLOADER PRESS INSPECTION BUFFER CONVEYOR.
    /// </summary>
    public enum EWarning
    {
        //--------- 1000 -> 1199 : Global ---------
        ET_ROOT = 1000,
        [Description("IN16,IN18,IN69,IN71")]
        DO_MAIN_DOOR_OPEN,
        [Description("IN17,IN19,IN70,IN72")]
        DO_MAIN_DOOR_INTERLOCK_ON,
        MO_MOVE_TARGET_POS_FAIL,
        [Description("IN11")]
        TE_MAIN_SENSOR_TEMP_OVER,
        [Description("IN04")]
        OP_MAIN_KEY_NOT_IN_AUTO_MODE,
        [Description("IN04")]
        OP_MAIN_MACHINE_NOT_IN_AUTO_MODE,

        //--------- 1200 -> 1999 : Mold ---------
        CY_MOLD_CHAMBER_OPEN_WARNING = 1200,
        CY_MOLD_CHAMBER_OPEN_FAIL,
        CY_MOLD_CHAMBER_CLOSE_WARNING,
        CY_MOLD_CHAMBER_CLOSE_FAIL,
        ET_MOLD_HEAD_USE_ERROR,

        MO_X_AXIS_HOME_TIMEOUT = 1300,
        MO_X_AXIS_READY_POS_TIMEOUT,
        MO_X_AXIS_INJECT_POS_TIMEOUT,
        MO_X_AXIS_DUMMY_POS_TIMEOUT,
        MO_X_AXIS_H13_DOT_WEIGHT_POS_TIMEOUT,
        MO_X_AXIS_H24_DOT_WEIGHT_POS_TIMEOUT,
        MO_X_AXIS_NEEDLE_CLEAN_TIMEOUT,

        MO_Y_AXIS_HOME_TIMEOUT = 1400,
        MO_Y_AXIS_READY_POS_TIMEOUT,
        MO_Y_AXIS_INJECT_POS_TIMEOUT,
        MO_Y_AXIS_DUMMY_POS_TIMEOUT,
        MO_Y_AXIS_H13_DOT_WEIGHT_POS_TIMEOUT,
        MO_Y_AXIS_H24_DOT_WEIGHT_POS_TIMEOUT,
        MO_Y_AXIS_NEEDLE_CLEAN_TIMEOUT,

        MO_Z1_AXIS_HOME_TIMEOUT = 1500,
        MO_Z1_AXIS_SAFE_POS_TIMEOUT,
        MO_SPD_H01_Z1_AXIS_INJECT_POS_TIMEOUT,
        MO_SPD_H01_Z1_AXIS_DUMMY_POS_TIMEOUT,
        MO_SPD_H01_Z1_AXIS_NEEDLE_CLEAN_POS_TIMEOUT,
        MO_SPD_H01_Z1_AXIS_DOT_WEIGHT_POS_TIMEOUT,
        MO_SPD_H01_Z1_AXIS_BUBBLE_POS_TIMEOUT,
        MO_SPD_H01_Z1_AXIS_ASSEMBLE_POS_TIMEOUT,
        MO_SPD_H01_Z1_AXIS_ADDTAIL_UP_TIMEOUT,

        MO_Z2_AXIS_HOME_TIMEOUT = 1600,
        MO_Z2_AXIS_SAFE_POS_TIMEOUT,
        MO_SPD_H02_Z2_AXIS_INJECT_POS_TIMEOUT,
        MO_SPD_H02_Z2_AXIS_DUMMY_POS_TIMEOUT,
        MO_SPD_H02_Z2_AXIS_NEEDLE_CLEAN_POS_TIMEOUT,
        MO_SPD_H02_Z2_AXIS_DOT_WEIGHT_POS_TIMEOUT,
        MO_SPD_H02_Z2_AXIS_BUBBLE_POS_TIMEOUT,
        MO_SPD_H02_Z2_AXIS_ASSEMBLE_POS_TIMEOUT,
        MO_SPD_H02_Z2_AXIS_ADDTAIL_UP_TIMEOUT,

        MO_Z3_AXIS_HOME_TIMEOUT = 1700,
        MO_Z3_AXIS_SAFE_POS_TIMEOUT,
        MO_SPD_H03_Z3_AXIS_INJECT_POS_TIMEOUT,
        MO_SPD_H03_Z3_AXIS_DUMMY_POS_TIMEOUT,
        MO_SPD_H03_Z3_AXIS_NEEDLE_CLEAN_POS_TIMEOUT,
        MO_SPD_H03_Z3_AXIS_DOT_WEIGHT_POS_TIMEOUT,
        MO_SPD_H03_Z3_AXIS_BUBBLE_POS_TIMEOUT,
        MO_SPD_H03_Z3_AXIS_ASSEMBLE_POS_TIMEOUT,
        MO_SPD_H03_Z3_AXIS_ADDTAIL_UP_TIMEOUT,

        MO_Z4_AXIS_HOME_TIMEOUT = 1800,
        MO_Z4_AXIS_SAFE_POS_TIMEOUT,
        MO_SPD_H04_Z4_AXIS_INJECT_POS_TIMEOUT,
        MO_SPD_H04_Z4_AXIS_DUMMY_POS_TIMEOUT,
        MO_SPD_H04_Z4_AXIS_NEEDLE_CLEAN_POS_TIMEOUT,
        MO_SPD_H04_Z4_AXIS_DOT_WEIGHT_POS_TIMEOUT,
        MO_SPD_H04_Z4_AXIS_BUBBLE_POS_TIMEOUT,
        MO_SPD_H04_Z4_AXIS_ASSEMBLE_POS_TIMEOUT,
        MO_SPD_H04_Z4_AXIS_ADDTAIL_UP_TIMEOUT,

        CY_BELLOW_DOWN_FAIL = 1900,
        CY_BELLOW_UP_FAIL,
        VC_CHAMBER_VAC_DETECT_WARNING,
        SE_CHAMBER_LEFT_JIG_TILT_DETECT,
        SE_CHAMBER_RIGHT_JIG_TILT_DETECT,
        EF_CHAMBER_LEFT_JIG_INJECT_NOT_FINISHED,
        EF_CHAMBER_RIGHT_JIG_INJECT_NOT_FINISHED,
        CY_NOZZLE_CLEAN_GRIP_FAIL,
        CY_NOZZLE_CLEAN_UNGRIP_FAIL,

        //--------- 2000 -> 2199 : Dry ---------
        CY_ANGLE_VALUE_CLOSE_FAIL = 2000,
        CY_ANGLE_VALUE_OPEN_FAIL,
        MO_DRYPUMP_RUN_TIMEOUT,
        VA_MACHINE_NEED_CALIBRATION,
        SE_JIG_DETECT_UNLOAD_FAIL,
        SE_LEFFT_JIG_TILT_STATE,
        SE_LEFT_JIG_NOT_DETECT,
        SE_RIGHT_JIG_TILT_STATE,
        SE_RIGHT_JIG_NOT_DETECT,

        //--------- 2200 -> 2399 : Head 1 ---------
        MO_SPD_H01_P1_AXIS_HOME_TIMEOUT = 2200,
        MO_SPD_H01_G1_AXIS_HOME_TIMEOUT,
        [Description("HEAD1_IN00")]
        CY_SPD_H01_PISTON_UP_FAIL,
        [Description("HEAD1_IN01")]
        CY_SPD_H01_PISTON_DOWN_FAIL,
        [Description("HEAD1_IN04")]
        MO_SPD_H01_ASSEMBLE_CHECK_TIMEOUT,
        [Description("HEAD1_IN04")]
        MO_SPD_H01_DISASSEMBLE_CHECK_TIMEOUT,
        VA_SPD_H01_BALANCE_NOT_STABLE,
        VA_SPD_H01_BALANCE_REQ_WEIGHT_FAIL,
        VA_SPD_H01_BALANCE_ZERO_FAIL,
        VA_SPD_H01_BALANCE_WEIGH_FAIL,
        MO_SPD_H01_P1_AXIS_BUBBLE_REMOVE_TIMEOUT,
        MO_SPD_H01_G1_AXIS_BUBBLE_REMOVE_TIMEOUT,
        MO_SPD_H01_INJECT_POS_OVER_BASE,
        [Description("HEAD1_IN05")]
        SE_SPD_H01_SYRING_NOT_DETECT,
        VA_SPD_H01_SYRING_AMOUNT_TIMEOVER,
        [Description("HEAD1_IN06")]
        SE_SPD_H01_SYRING_AIR_NOT_DETECT,

        //--------- 2400 -> 2599 : Head 2 ---------
        MO_SPD_H02_P2_AXIS_HOME_TIMEOUT = 2400,
        MO_SPD_H02_G2_AXIS_HOME_TIMEOUT,
        [Description("HEAD2_IN00")]
        CY_SPD_H02_PISTON_UP_FAIL,
        [Description("HEAD2_IN01")]
        CY_SPD_H02_PISTON_DOWN_FAIL,
        [Description("HEAD2_IN04")]
        MO_SPD_H02_ASSEMBLE_CHECK_TIMEOUT,
        [Description("HEAD2_IN04")]
        MO_SPD_H02_DISASSEMBLE_CHECK_TIMEOUT,
        VA_SPD_H02_BALANCE_NOT_STABLE,
        VA_SPD_H02_BALANCE_REQ_WEIGHT_FAIL,
        VA_SPD_H02_BALANCE_ZERO_FAIL,
        VA_SPD_H02_BALANCE_WEIGH_FAIL,
        MO_SPD_H02_P2_AXIS_BUBBLE_REMOVE_TIMEOUT,
        MO_SPD_H02_G2_AXIS_BUBBLE_REMOVE_TIMEOUT,
        MO_SPD_H02_INJECT_POS_OVER_BASE,
        [Description("HEAD2_IN05")]
        SE_SPD_H02_SYRING_NOT_DETECT,
        VA_SPD_H02_SYRING_AMOUNT_TIMEOVER,
        [Description("HEAD2_IN06")]
        SE_SPD_H02_SYRING_AIR_NOT_DETECT,

        //--------- 2600 -> 2799 : Head 3 ---------
        MO_SPD_H03_P3_AXIS_HOME_TIMEOUT = 2600,
        MO_SPD_H03_G3_AXIS_HOME_TIMEOUT,
        [Description("HEAD3_IN00")]
        CY_SPD_H03_PISTON_UP_FAIL,
        [Description("HEAD3_IN01")]
        CY_SPD_H03_PISTON_DOWN_FAIL,
        [Description("HEAD3_IN04")]
        MO_SPD_H03_ASSEMBLE_CHECK_TIMEOUT,
        [Description("HEAD3_IN04")]
        MO_SPD_H03_DISASSEMBLE_CHECK_TIMEOUT,
        VA_SPD_H03_BALANCE_NOT_STABLE,
        VA_SPD_H03_BALANCE_REQ_WEIGHT_FAIL,
        VA_SPD_H03_BALANCE_ZERO_FAIL,
        VA_SPD_H03_BALANCE_WEIGH_FAIL,
        MO_SPD_H03_P3_AXIS_BUBBLE_REMOVE_TIMEOUT,
        MO_SPD_H03_G3_AXIS_BUBBLE_REMOVE_TIMEOUT,
        MO_SPD_H03_INJECT_POS_OVER_BASE,
        [Description("HEAD3_IN05")]
        SE_SPD_H03_SYRING_NOT_DETECT,
        VA_SPD_H03_SYRING_AMOUNT_TIMEOVER,
        [Description("HEAD3_IN06")]
        SE_SPD_H03_SYRING_AIR_NOT_DETECT,

        //--------- 2800 -> 2999 : Head 4 ---------
        MO_SPD_H04_P4_AXIS_HOME_TIMEOUT = 2800,
        MO_SPD_H04_G4_AXIS_HOME_TIMEOUT,
        [Description("HEAD4_IN00")]
        CY_SPD_H04_PISTON_UP_FAIL,
        [Description("HEAD4_IN01")]
        CY_SPD_H04_PISTON_DOWN_FAIL,
        [Description("HEAD4_IN04")]
        MO_SPD_H04_ASSEMBLE_CHECK_TIMEOUT,
        [Description("HEAD4_IN04")]
        MO_SPD_H04_DISASSEMBLE_CHECK_TIMEOUT,
        VA_SPD_H04_BALANCE_NOT_STABLE,
        VA_SPD_H04_BALANCE_REQ_WEIGHT_FAIL,
        VA_SPD_H04_BALANCE_ZERO_FAIL,
        VA_SPD_H04_BALANCE_WEIGH_FAIL,
        MO_SPD_H04_P4_AXIS_BUBBLE_REMOVE_TIMEOUT,
        MO_SPD_H04_G4_AXIS_BUBBLE_REMOVE_TIMEOUT,
        MO_SPD_H04_INJECT_POS_OVER_BASE,
        [Description("HEAD4_IN05")]
        SE_SPD_H04_SYRING_NOT_DETECT,
        VA_SPD_H04_SYRING_AMOUNT_TIMEOVER,
        [Description("HEAD4_IN06")]
        SE_SPD_H04_SYRING_AIR_NOT_DETECT,
    }
}
