<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.17763.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <Configurations>Debug;Release;Simulation</Configurations>
    <BaseOutputPath></BaseOutputPath>
    <ApplicationIcon>TopIcon.ico</ApplicationIcon>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Simulation|AnyCPU'">
    <DefineConstants>$(DefineConstants);SIMULATION</DefineConstants>
    <XamlDebuggingInformation>True</XamlDebuggingInformation>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Converters\JsonConverters\**" />
    <Compile Remove="Defines\Process\Step\04.OutWorkConveyorProcess\**" />
    <Compile Remove="Defines\Recipes\**" />
    <Compile Remove="Process\Define\**" />
    <Compile Remove="Process\Steps\**" />
    <EmbeddedResource Remove="Converters\JsonConverters\**" />
    <EmbeddedResource Remove="Defines\Process\Step\04.OutWorkConveyorProcess\**" />
    <EmbeddedResource Remove="Defines\Recipes\**" />
    <EmbeddedResource Remove="Process\Define\**" />
    <EmbeddedResource Remove="Process\Steps\**" />
    <None Remove="Converters\JsonConverters\**" />
    <None Remove="Defines\Process\Step\04.OutWorkConveyorProcess\**" />
    <None Remove="Defines\Recipes\**" />
    <None Remove="Process\Define\**" />
    <None Remove="Process\Steps\**" />
    <Page Remove="Converters\JsonConverters\**" />
    <Page Remove="Defines\Process\Step\04.OutWorkConveyorProcess\**" />
    <Page Remove="Defines\Recipes\**" />
    <Page Remove="Process\Define\**" />
    <Page Remove="Process\Steps\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Resource\Images\DryPump_IsoView.png" />
    <None Remove="Resource\Images\Inject_IsoView.png" />
    <None Remove="Resource\Images\MoldInjection_TopView.png" />
    <None Remove="Resource\Images\SPDHead_IsoView.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resource\Images\DryPump_IsoView.png" />
    <Resource Include="Resource\Images\Inject_IsoView.png" />
    <Resource Include="Resource\Images\MoldInjection_TopView.png" />
	  
    <Resource Include="Resource\Images\Blance.png" />
    <Resource Include="Resource\Images\EMS BUTTON GRAY.png" />
    <Resource Include="Resource\Images\EMS BUTTON.png" />
    <Resource Include="Resource\Images\HEAD.png" />
    <Resource Include="Resource\Images\MachineView.png" />
    <Resource Include="Resource\Images\PowerON.png" />
    <Resource Include="Resource\Images\BONDINGJIG.png" />
    <Resource Include="Resource\Images\CHAMBER CLOSE.png" />
    <Resource Include="Resource\Images\CHAMBER OPEN.png" />
	  
    <Resource Include="Resource\Images\SPDHead_IsoView.png" />
    <Resource Include="TopIcon.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
	  <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.2" />
	  <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.2" />
	  <PackageReference Include="OpenCvSharp4" Version="4.11.0.20250507" />
	  <PackageReference Include="OpenCvSharp4.runtime.win" Version="4.11.0.20250507" />
	  <PackageReference Include="OpenCvSharp4.WpfExtensions" Version="4.11.0.20250507" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EQX.Core\EQX.Core\EQX.Core.csproj" />
    <ProjectReference Include="..\EQX.Device\EQX.Device\EQX.Device.csproj" />
    <ProjectReference Include="..\EQX.InOut\EQX.InOut.InputSimulation\EQX.InOut.InputSimulation.csproj" />
    <ProjectReference Include="..\EQX.InOut\EQX.InOut\EQX.InOut.csproj" />
    <ProjectReference Include="..\EQX.Motion\EQX.Motion\EQX.Motion.csproj" />
    <ProjectReference Include="..\EQX.Process\EQX.Process\EQX.Process.csproj" />
    <ProjectReference Include="..\EQX.ThirdParty\EQX.ThirdParty\EQX.ThirdParty.csproj" />
    <ProjectReference Include="..\EQX.UI\EQX.UI\EQX.UI.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="MoldInjectionLog.config">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
